apiVersion: v1
kind: Service
metadata:
  name: my-service
  labels:
    name: my-service
    tier: front-end
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 3001
      nodePort: 30003
  selector:
    name: my-pod
    tier: front-end

